//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CypherShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIETDONTHANGs = new HashSet<CHITIETDONTHANG>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<decimal> Giaban { get; set; }
        public Nullable<decimal> Gianhap { get; set; }
        public Nullable<int> Giamgia { get; set; }
        public string Mota { get; set; }
        public string Anhbia { get; set; }
        public Nullable<System.DateTime> Ngaycapnhat { get; set; }
        public Nullable<int> Soluongton { get; set; }
        public Nullable<int> MaTL { get; set; }
        public Nullable<int> MaNSX { get; set; }
        public string MauSac { get; set; }
        public string SCPU { get; set; }
        public string CPU { get; set; }
        public string DoHoa { get; set; }
        public string RAM { get; set; }
        public string SSD { get; set; }
        public string Trongluong { get; set; }
        public string Pin { get; set; }
        public string ManHinh { get; set; }
        public string PhanGiai { get; set; }
        public string HDH { get; set; }
        public string CamUng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONTHANG> CHITIETDONTHANGs { get; set; }
        public virtual NHASANXUAT NHASANXUAT { get; set; }
        public virtual THELOAI THELOAI { get; set; }
    }
}
